services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-spliceai-loader}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - db:/var/lib/postgresql/data

  spliceai:
    image: us-central1-docker.pkg.dev/spliceai-lookup-412920/docker/spliceai-38:latest
    init: true
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DSN: "host=db user=${POSTGRES_USER:-spliceai-loader} dbname=${POSTGRES_USER:-spliceai-loader}"
      CONCURRENCY: 4
    runtime: nvidia

  pangolin:
    image: us-central1-docker.pkg.dev/spliceai-lookup-412920/docker/pangolin-38:latest
    init: true
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DSN: "host=db user=${POSTGRES_USER:-spliceai-loader} dbname=${POSTGRES_USER:-spliceai-loader}"
      CONCURRENCY: 4
    runtime: nvidia

volumes:
  db:
