services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-spliceai-loader}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - db:/var/lib/postgresql/data

  spliceai:
    image: us-central1-docker.pkg.dev/spliceai-lookup-412920/docker/spliceai-38:latest
    init: true
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DSN: "host=db user=${POSTGRES_USER:-spliceai-loader} dbname=${POSTGRES_USER:-spliceai-loader}"
    ports:
      - "8088:8080"

  pangolin:
    image: us-central1-docker.pkg.dev/spliceai-lookup-412920/docker/pangolin-38:latest
    init: true
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DSN: "host=db user=${POSTGRES_USER:-spliceai-loader} dbname=${POSTGRES_USER:-spliceai-loader}"
    ports:
      - "8089:8080"
volumes:
  db:
